"""Cuentas de arranque basadas en el Plan General Contable de PYMES.

Se cargan al inicializar una base de datos vacía. El usuario puede crear
cuentas y subcuentas adicionales desde la aplicación o la API.
"""

PGC_CUENTAS = [
    # Grupo 1: Financiación básica
    ("100", "Capital social"),
    ("102", "Capital"),
    ("112", "Reserva legal"),
    ("113", "Reservas voluntarias"),
    ("118", "Aportaciones de socios"),
    ("120", "Remanente"),
    ("121", "Resultados negativos de ejercicios anteriores"),
    ("129", "Resultado del ejercicio"),
    ("170", "Deudas a largo plazo con entidades de crédito"),
    ("171", "Deudas a largo plazo"),
    # Grupo 2: Activo no corriente
    ("206", "Aplicaciones informáticas"),
    ("210", "Terrenos y bienes naturales"),
    ("211", "Construcciones"),
    ("212", "Instalaciones técnicas"),
    ("213", "Maquinaria"),
    ("214", "Utillaje"),
    ("215", "Otras instalaciones"),
    ("216", "Mobiliario"),
    ("217", "Equipos para procesos de información"),
    ("218", "Elementos de transporte"),
    ("219", "Otro inmovilizado material"),
    ("280", "Amortización acumulada del inmovilizado intangible"),
    ("281", "Amortización acumulada del inmovilizado material"),
    # Grupo 3: Existencias
    ("300", "Mercaderías"),
    # Grupo 4: Acreedores y deudores
    ("400", "Proveedores"),
    ("401", "Proveedores, efectos comerciales a pagar"),
    ("410", "Acreedores por prestaciones de servicios"),
    ("430", "Clientes"),
    ("431", "Clientes, efectos comerciales a cobrar"),
    ("436", "Clientes de dudoso cobro"),
    ("440", "Deudores"),
    ("460", "Anticipos de remuneraciones"),
    ("465", "Remuneraciones pendientes de pago"),
    ("470", "Hacienda Pública, deudora por diversos conceptos"),
    ("472", "Hacienda Pública, IVA soportado"),
    ("473", "Hacienda Pública, retenciones y pagos a cuenta"),
    ("475", "Hacienda Pública, acreedora por conceptos fiscales"),
    ("4750", "Hacienda Pública, acreedora por IVA"),
    ("4751", "Hacienda Pública, acreedora por retenciones practicadas"),
    ("476", "Organismos de la Seguridad Social, acreedores"),
    ("477", "Hacienda Pública, IVA repercutido"),
    # Grupo 5: Cuentas financieras
    ("520", "Deudas a corto plazo con entidades de crédito"),
    ("523", "Proveedores de inmovilizado a corto plazo"),
    ("551", "Cuenta corriente con socios y administradores"),
    ("555", "Partidas pendientes de aplicación"),
    ("570", "Caja, euros"),
    ("572", "Bancos e instituciones de crédito c/c vista, euros"),
    # Grupo 6: Compras y gastos
    ("600", "Compras de mercaderías"),
    ("602", "Compras de otros aprovisionamientos"),
    ("607", "Trabajos realizados por otras empresas"),
    ("621", "Arrendamientos y cánones"),
    ("622", "Reparaciones y conservación"),
    ("623", "Servicios de profesionales independientes"),
    ("624", "Transportes"),
    ("625", "Primas de seguros"),
    ("626", "Servicios bancarios y similares"),
    ("627", "Publicidad, propaganda y relaciones públicas"),
    ("628", "Suministros"),
    ("629", "Otros servicios"),
    ("630", "Impuesto sobre beneficios"),
    ("631", "Otros tributos"),
    ("640", "Sueldos y salarios"),
    ("642", "Seguridad Social a cargo de la empresa"),
    ("662", "Intereses de deudas"),
    ("678", "Gastos excepcionales"),
    ("680", "Amortización del inmovilizado intangible"),
    ("681", "Amortización del inmovilizado material"),
    # Grupo 7: Ventas e ingresos
    ("700", "Ventas de mercaderías"),
    ("705", "Prestaciones de servicios"),
    ("708", "Devoluciones de ventas y operaciones similares"),
    ("752", "Ingresos por arrendamientos"),
    ("769", "Otros ingresos financieros"),
    ("778", "Ingresos excepcionales"),
]
